services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    user: root # запускаємо як root, щоб мати права на створення директорій
    environment:
      - SPARK_MODE=master
      - HOME=/tmp # використовуємо /tmp для Ivy локальних репозиторіїв
    ports:
      - "8088:8080" # Spark Master UI
      - "7077:7077" # Spark Master port
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    user: root # запускаємо як root
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    user: root # запускаємо як root
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
